include:
  # TOTEM
  ## reset 
  - board: seeeduino_xiao_ble
    shield: settings_reset

  ## left central
  - board: seeeduino_xiao_ble
    shield: totem_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: totem_standalone_left_central

  - board: seeeduino_xiao_ble
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem_standalone_right_peripheral

 ## dongle central 
  - board: seeeduino_xiao_ble
    shield: totem_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem_dongle_left_peripheral

  - board: seeeduino_xiao_ble
    shield: totem_dongle
    snippet: studio-rpc-usb-uart
    artifact-name: totem_dongle_central
